import Light from "../assets/img/Light.png";

export const particle = {
  autoPlay: true,
  background: {
    color: { value: "#070834" },
    image: "",
    position: "50% 50%",
    repeat: "no-repeat",
    size: "cover",
    opacity: 1,
  },
  defaultThemes: {},
  delay: 0,
  fullScreen: { enable: true, zIndex: 1 },
  detectRetina: true,
  duration: 0,
  fpsLimit: 120,
  // interactivity: {
  //   detectsOn: "window",
  //   events: {
  //     onClick: { enable: true, mode: "repulse" },
  //     onDiv: { selectors: [], enable: false, mode: [], type: "circle" },
  //     onHover: {
  //       enable: true,
  //       mode: "bubble",
  //       parallax: { enable: false, force: 2, smooth: 10 },
  //     },
  //     resize: { delay: 0.5, enable: true },
  //   },
  //   modes: {
  //     trail: { delay: 1, pauseOnStop: false, quantity: 1 },
  //     attract: {
  //       distance: 200,
  //       duration: 0.4,
  //       easing: "ease-out-quad",
  //       factor: 1,
  //       maxSpeed: 50,
  //       speed: 1,
  //     },
  //     bounce: { distance: 200 },
  //     bubble: {
  //       distance: 400,
  //       duration: 0.3,
  //       mix: false,
  //       opacity: 1,
  //       size: 4,
  //       divs: { distance: 200, duration: 0.4, mix: false, selectors: [] },
  //     },
  //     connect: { distance: 80, links: { opacity: 0.5 }, radius: 60 },
  //     grab: {
  //       distance: 400,
  //       links: { blink: false, consent: false, opacity: 0.5 },
  //     },
  //     push: { default: true, groups: [], quantity: 4 },
  //     remove: { quantity: 2 },
  //     repulse: {
  //       distance: 200,
  //       duration: 0.4,
  //       factor: 100,
  //       speed: 1,
  //       maxSpeed: 50,
  //       easing: "ease-out-quad",
  //       divs: {
  //         distance: 200,
  //         duration: 0.4,
  //         factor: 100,
  //         speed: 1,
  //         maxSpeed: 50,
  //         easing: "ease-out-quad",
  //         selectors: [],
  //       },
  //     },
  //     slow: { factor: 3, radius: 200 },
  //     light: {
  //       area: {
  //         gradient: {
  //           start: { value: "#ffffff" },
  //           stop: { value: "#000000" },
  //         },
  //         radius: 1000,
  //       },
  //       shadow: { color: { value: "#000000" }, length: 2000 },
  //     },
  //   },
  // },
  manualParticles: [],
  particles: {
    bounce: {
      horizontal: {
        random: { enable: false, minimumValue: 1 },
        value: 1,
      },
      vertical: {
        random: { enable: false, minimumValue: 1 },
        value: 0,
      },
    },

    collisions: {
      absorb: { speed: 2 },
      bounce: {
        horizontal: {
          random: { enable: false, minimumValue: 1 },
          value: 2,
        },
        vertical: {
          random: { enable: false, minimumValue: 1 },
          value: 1,
        },
      },
      enable: false,
      maxSpeed: 10,
      mode: "bounce",
      overlap: { enable: false, retries: 0 },
    },
    color: {
      value: "#e6c17a",

      animation: {
        h: {
          count: 0,
          enable: false,
          offset: 0,
          speed: 1,
          delay: 0,
          decay: 0,
          sync: true,
        },
        s: {
          count: 0,
          enable: false,
          offset: 0,
          speed: 1,
          delay: 0,
          decay: 0,
          sync: true,
        },
        l: {
          count: 0,
          enable: false,
          offset: 0,
          speed: 1,
          delay: 0,
          decay: 0,
          sync: true,
        },
      },
    },
    groups: {},
    move: {
      angle: { offset: 0, value: 90 },
      attract: {
        distance: 200,
        enable: false,
        rotate: { x: 600, y: 1200 },
      },
      center: { x: 50, y: 50, mode: "percent", radius: 0 },
      decay: 0,
      distance: [],
      direction: "bottom",
      drift: 0,
      enable: true,
      gravity: {
        acceleration: 9.81,
        enable: false,
        inverse: false,
        maxSpeed: 5,
      },
      path: {
        clamp: true,
        delay: { random: { enable: false, minimumValue: 0 }, value: 0 },
        enable: false,
        options: {},
      },
      outModes: {
        default: "out",
        bottom: "out",
        left: "out",
        right: "out",
        top: "out",
      },
      random: false,
      size: false,
      speed: { min: 2, max: 5 },
      spin: { acceleration: 0, enable: false },
      straight: true,
      trail: { enable: false, length: 10, fill: {} },
      vibrate: false,
      warp: false,
    },
    number: {
      density: { enable: true, width: 400, height: 1000 },
      limit: 6,
      value: 10,
    },
    opacity: {
      random: { enable: false, minimumValue: 1 },
      value: { min: 0.2, max: 0.8 },
      animation: {
        count: 0,
        enable: true,
        speed: 1,
        decay: 0,
        delay: 0,
        sync: false,
        mode: "auto",
        startValue: "random",
        destroy: "none",
        minimumValue: 0.5,
      },
    },
    reduceDuplicates: false,
    shadow: {
      blur: 0,
      color: { value: "#000" },
      enable: false,
      offset: { x: 0, y: 0 },
    },
    shape: {
      type: "images",
      options: {
        images: {
          src: "https://raw.githubusercontent.com/thaya2000/image_upload/main/Circle_Animation.png",
          width: 100,
          height: 100,
        },
      },
    },
    size: {
      random: { enable: false, value: 5 },
      value: 100,
      animation: {
        count: 0,
        enable: true,
        speed: 100,
        decay: 0,
        delay: 0,
        sync: true,
        mode: "auto",
        startValue: 5,
        destroy: "none",
        minimumValue: 10,
      },
    },
    stroke: { width: 0 },
    zIndex: {
      random: { enable: false, minimumValue: 0 },
      value: 0,
      opacityRate: 1,
      sizeRate: 1,
      velocityRate: 1,
    },
    destroy: {
      bounds: {},
      mode: "collision", // Change this line
      split: {
        count: 2,
        factor: { random: { enable: true, minimumValue: 0 }, value: 3 },
        rate: {
          random: { enable: true, minimumValue: 0 },
          value: { min: 4, max: 9 },
        },
        sizeOffset: true,
      },
    },
    roll: {
      darken: { enable: false, value: 0 },
      enable: false,
      enlighten: { enable: false, value: 0 },
      mode: "vertical",
      speed: 25,
    },
    tilt: {
      random: { enable: false, minimumValue: 0 },
      value: 0,
      animation: { enable: false, speed: 0, decay: 0, sync: false },
      direction: "clockwise",
      enable: false,
    },
    twinkle: {
      lines: { enable: false, frequency: 0.05, opacity: 1 },
      particles: { enable: true, frequency: 0.001, opacity: 1 },
    },
    wobble: { distance: 5, enable: false, speed: { angle: 50, move: 10 } },
    life: {
      count: 0,
      delay: {
        random: { enable: false, minimumValue: 0 },
        value: 0,
        sync: false,
      },
      duration: {
        random: { enable: false, minimumValue: 0.0001 },
        value: 0,
        sync: false,
      },
    },
    rotate: {
      random: { enable: false, minimumValue: 0 },
      value: 0,
      animation: { enable: false, speed: 0, decay: 0, sync: false },
      direction: "clockwise",
      path: false,
    },
    orbit: {
      animation: {
        count: 0,
        enable: false,
        speed: 1,
        decay: 0,
        delay: 0,
        sync: false,
      },
      enable: false,
      opacity: 1,
      rotation: { random: { enable: false, minimumValue: 0 }, value: 45 },
      width: 1,
    },
    links: {
      blink: false,
      color: { value: "#ffffff" },
      consent: false,
      distance: 500,
      enable: false,
      frequency: 1,
      opacity: 0.4,
      shadow: { blur: 5, color: { value: "#000" }, enable: false },
      triangles: { enable: false, frequency: 1 },
      width: 2,
      warp: false,
    },
    repulse: {
      random: { enable: false, minimumValue: 0 },
      value: 100,
      enabled: false,
      distance: 10,
      duration: 30,
      factor: 100,
      speed: 10,
    },
  },
  pauseOnBlur: false,
  pauseOnOutsideViewport: true,
  responsive: [],
  smooth: false,
  style: {},
  themes: [],
  zLayers: 100,
  motion: { disable: true, reduce: { factor: 4, value: true } },
};
